spring.application.name=backend

# Configuracion de PostgreSQL Neon
spring.datasource.url=jdbc:postgresql://ep-muddy-hat-afinhfq3-pooler.c-2.us-west-2.aws.neon.tech/sushi_room?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NEaBI83TKRUF
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE



#PARA PRODUCCION
sendgrid.api.key=${SENDGRID_API_KEY}
email.from=${EMAIL_FROM}