spring.application.name=backend

# Configuracion de PostgreSQL Neon
spring.datasource.url=jdbc:postgresql://ep-muddy-hat-afinhfq3-pooler.c-2.us-west-2.aws.neon.tech/sushi_room?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NEaBI83TKRUF
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configuración de email - USA TU CORREO Y LA CONTRASEÑA GENERADA
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true